spring.application.name=SpringAI
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=openai/gpt-4o
spring.ai.openai.base-url=https://openrouter.ai/api
#spring.ai.ollama.chat.option.model
